### ISSUE TITLE
aptX LL support

### ISSUE THREAD

**Issue by bitrevo** [EHfive/pulseaudio-modules-bt#29]
Any plan to support aptX LL (Low Latency) mode?

**Comment by EHfive** [comment]
> https://github.com/pali/libopenaptx/issues/1#issuecomment-448005061

Seems aptX LL & aptX Classic share the encoding/decoding processes.

If someone can help to test, aptX LL support could be added to this module.

**Comment by morguldir** [comment]
I can help, i have aptx LL capable headphones, just tell me what to do.

**Comment by EHfive** [comment]
Thanks all.

When I look into aptx LL configuration headers, I found that aptX LL have 7 more parameters than aptX.
So let other one to test it would be inefficient, 
I decide to put down it now.

```C
typedef struct {
	uint8_t reserved;
	uint8_t target_level2;
	uint8_t target_level1;
	uint8_t initial_level2;
	uint8_t initial_level1;
	uint8_t sra_max_rate;
	uint8_t sra_avg_time;
	uint8_t good_working_level2;
	uint8_t good_working_level1;
} __attribute__ ((packed)) a2dp_aptx_ll_new_caps_t;

typedef struct {
	a2dp_vendor_codec_t info;
	uint8_t channel_mode:4;
	uint8_t frequency:4;
} __attribute__ ((packed)) a2dp_aptx_t;

typedef struct {
	a2dp_vendor_codec_t info;
	uint8_t direction;
	uint8_t sink_frequency:4;
	uint8_t source_frequency:4;
} __attribute__ ((packed)) a2dp_faststream_t;

typedef struct {
	a2dp_vendor_codec_t info;
	uint8_t channel_mode:4;
	uint8_t frequency:4;
	uint8_t bidirect_link:1;
	uint8_t has_new_caps:1;
	uint8_t reserved:6;
	a2dp_aptx_ll_new_caps_t new_caps[0];
} __attribute__ ((packed)) a2dp_aptx_ll_t;
```

**Comment by a-rasinski** [comment]
@EHfive Hey! Awesome work you did with this pa module.
Would really love to have aptx-ll supported. What's the main issue with implementing this? If it's just some tedious work maybe I could help with little guidance from your side. I've been able to build the project and successfully get it running and able to test. Also I have aptx-ll compat device.

**Comment by noygal** [comment]
@EHfive Thanks for the great work!

Sadly `aptx-ll` is 'forgotten' on many audiophile devices due to its lower sound quality and licence structure of codex family. The codex has a real value to htpc/gaming setups, where you can place `raspberry pi` (or other boards) that would receive the output sound from tv/receiver and broadcast it in the `aptx-ll` format. I have tried multiple BT solutions, built-in and externals, with multiple streaming codexes, none except `aptx-ll` offer the level of latency acceptable for video/gaming.

I would like to help out with this feature, but I'm a js developer myself with a past experience from around 10 year ago at C++ (real time image processing). If you can spare the time and have the will, please share some links on the specs/structure of the codex and what need to be done, so I (or someone else) could follow this up.

In any case it would be nice to reopen this issue and add `help needed` tag to it.

**Comment by ValdikSS** [comment]
I've quick-patched @EHfive's module to support aptX Low Latency and it worked with stock libopenaptx. I've got about 50-65 ms of latency, which is much lower than with stock aptX.
Mailed @pali and @EHfive the Bluetooth dump with aptX LL traffic.

**Comment by noygal** [comment]
> I've quick-patched @EHfive's module to support aptX Low Latency and it worked with stock libopenaptx. I've got about 50-65 ms of latency, which is much lower than with stock aptX.
> Mailed @pali and @EHfive the Bluetooth dump with aptX LL traffic.

@ValdikSS can you share your repository? I'll love to test this out.

**Comment by BAAZKonqi** [comment]
Hi, did the the aptX LL feature make it into the module?
Otherwise I'd really like to see your patched one. @ValdikSS

**Comment by odensc** [comment]
@BAAZKonqi nope, but there is a [patch for it upstream](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/227) (I haven't personally tested it)
