### ISSUE TITLE
A2DP Sink dont support microphone

### ISSUE THREAD

**Issue by brauliobo** [EHfive/pulseaudio-modules-bt#32]
How can I use the microphone in a good quality as well? When I switch to A2DP Sink it doesn't show any recording device for my Mi Sports BT Earphones

**Comment by EHfive** [comment]
>  When I switch to A2DP Sink it doesn't show any recording device for my Mi Sports BT Earphones

It's not a bug or something,
It's a feature.

> How can I use the microphone in a good quality as well?

You can't. The use of HSP/HSF is phone calls, not music.

**Comment by brauliobo** [comment]
Can good codecs be used with HSP/HSF?

**Comment by EHfive** [comment]
> Can good codecs be used with HSP/HSF?

Can't... 

https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Advanced_Audio_Distribution_Profile_(A2DP)

**Comment by brauliobo** [comment]
Do you know why Android have a better bluetooth call quality?

**Comment by EHfive** [comment]
> Do you know why Android have a better bluetooth call quality?

I'm not familiar with Android 's implements. Maybe Android has a higher audio sample frequency setting in HSP/HSF and a better I/O.

**Comment by venatiodecorus** [comment]
I just built this and got it installed to use my microphone but I guess I'm out of luck! Thanks for your work anyways I'm sure I'll enjoy the higher quality codecs. Is there any way to adjust HSP/HFP profile to sound better at all? Or any way to use a microphone while listening to high quality audio on Linux over Bluetooth? Or is my only option to go wired or with a different wireless protocol?

Thanks again for your work and I appreciate if you take any time to answer my questions.

**Comment by gombosg** [comment]
No, HSP is always bad quality, like a phone. It's an old codec.
For my Sennheiser HD4.50BTNC, it switches to HSP when using the microphone. On Linux and on my phone, too. So I think this is true for all headsets, since they can only have 1 BT connection to the same computer (phone etc.) at a time and A2DP is [unidirectional](https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles#Advanced_Audio_Distribution_Profile_(A2DP)).

**Comment by brauliobo** [comment]
@gombosg android HSP quality is surely better! there must be a setting/limitation to make linux/pulseaudio as good as android

**Comment by EHfive** [comment]
The sample rate of HSP on pulseaudio bluetooth modules is 8000Hz.
You could try alsa-bluez which support HSP 1.6 "wideband speech" mSBC codec at 16 kHz.

**Comment by brauliobo** [comment]
@EHfive just asked them at https://github.com/Arkq/bluez-alsa/issues/187 on how to configure, have you ever done it?

**Comment by dceee** [comment]
> You could try alsa-bluez which support HSP 1.6 "wideband speech" mSBC codec at 16 kHz.

This is exactly what I was missing on my Linux desktops. Is this a pulseaudio, alsa or a hardware limitation? My Sennheiser PXC-550 sound way better on my Android devices when using in headset mode (full duplex, not A2DP). I guess they are using the HSP 1.6 mSBC profile.
I tried the bluez-alsa approach. But since it states that it cannot run alongside pulseaudio, it's not a solution for me.

**Comment by brauliobo** [comment]
@dceee thanks for confirming!

**Comment by bhack** [comment]
Please upvote the feature at https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/254

**Comment by bhack** [comment]
See also https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/issues/776
